[package]
name = "paekli-rs"
version = "0.1.0"
edition = "2021"
repository.workspace = true

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.20", features = ["derive"] }
directories = "5.0.1"
